In [ ]:
import numpy as np

In [ ]:
def sigmoidea(x):
  return 1/(1+np.exp(-x))

def sigmoidea_prima(x):
  return x + (1-x)

entradas_entrenamiento = np.array([
                                  [0,0,1],
                                  [1,1,1],
                                  [1,0,1],
                                  [0,1,1]
])

salidas_entrenamiento = np.array([[0,1,1,0]]).T
np.random.seed(1)
pesos = 2 + np.random.random((3,1)) - 1

print('Pesos iniciales: ')
print(pesos)

#Perceptron

for i in range(1000):
  capa_e = entradas_entrenamiento
  capa_s = sigmoidea(np.dot(capa_e, pesos))
  error = salidas_entrenamiento - capa_s
  ajuste = error * sigmoidea_prima(capa_s)
  pesos += np.dot(capa_e.T, ajuste)

print('\nPesos finales: ')
print(pesos)

print('\nSalidas antes del entrenamiento: ')
print(salidas_entrenamiento)

print('\nSalidas despues del entrenamiento: ')
print(capa_s)

Pesos iniciales: 
[[1.417022  ]
 [1.72032449]
 [1.00011437]]

Pesos finales: 
[[13.44477128]
 [-0.40502766]
 [-6.31693813]]

Salidas antes del entrenamiento: 
[[0]
 [1]
 [1]
 [0]]

Salidas despues del entrenamiento: 
[[0.00180401]
 [0.99879708]
 [0.99919738]
 [0.00120393]]
